package entidades;
// Generated 14/07/2019 01:41:50 AM by Hibernate Tools 4.3.1



/**
 * Vacuna generated by hbm2java
 */
public class Vacuna  implements java.io.Serializable {


     private Integer idVacuna;
     private String nombreComercial;
     private String nombreGenerico;
     private String nroRegistro;
     private char tipoVacuna;
     private String patogeno;
     private String precio;
     private int edad;

    public Vacuna() {
    }

    public Vacuna(String nombreComercial, String nombreGenerico, String nroRegistro, char tipoVacuna, String patogeno, String precio, int edad) {
       this.nombreComercial = nombreComercial;
       this.nombreGenerico = nombreGenerico;
       this.nroRegistro = nroRegistro;
       this.tipoVacuna = tipoVacuna;
       this.patogeno = patogeno;
       this.precio = precio;
       this.edad = edad;
    }
   
    public Integer getIdVacuna() {
        return this.idVacuna;
    }
    
    public void setIdVacuna(Integer idVacuna) {
        this.idVacuna = idVacuna;
    }
    public String getNombreComercial() {
        return this.nombreComercial;
    }
    
    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }
    public String getNombreGenerico() {
        return this.nombreGenerico;
    }
    
    public void setNombreGenerico(String nombreGenerico) {
        this.nombreGenerico = nombreGenerico;
    }
    public String getNroRegistro() {
        return this.nroRegistro;
    }
    
    public void setNroRegistro(String nroRegistro) {
        this.nroRegistro = nroRegistro;
    }
    public char getTipoVacuna() {
        return this.tipoVacuna;
    }
    
    public void setTipoVacuna(char tipoVacuna) {
        this.tipoVacuna = tipoVacuna;
    }
    public String getPatogeno() {
        return this.patogeno;
    }
    
    public void setPatogeno(String patogeno) {
        this.patogeno = patogeno;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }


}


